# Generated by Django 4.1.7 on 2023-03-14 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0002_alter_urlparser_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlparser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="urlparser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
